// config.js
// 定数の定義

export const config = {
  version: 'v3.0.0',
  releaseDate: '2025.12.01',
  copyright: 'Copyright 2021-2025 Kanagawa Institute of Technology',
  servers: [
    { url: 'https://webapiechonet.com/elapi/v1', apiKeyType: 'X-Elapi-key' },
    { url: 'https://dev.webapiechonet.com/elapi/v1', apiKeyType: 'X-Elapi-key' },
    { url: 'https://www.smarthouse-center.org/elapi/v1', apiKeyType: 'Authorization' },
  ],
  // ログをダウンロードする場合のファイル名
  fileName4Log: 'log_elapi.txt',
  forConsortium: false,
  // デバイス追加に表示するデバイス名のリスト
  addDeviceList: [
    'airCleaner',
    'airConditionerVentilationFan',
    'bathHeatingStatusSensor',
    'bathroomHeaterDryer',
    'bidirHvSmartElectricEnergyMeter',
    'co2Sensor',
    'coldOrHotWaterHeatSourceEquipment',
    'commercialAirConditionerIndoorUnit',
    'commercialAirConditionerOutdoorUnit',
    'commercialShowcase',
    'commercialShowcaseOutdoorUnit',
    'controller',
    'cookingHeater',
    'crimePreventionSensor',
    'currentSensor',
    'drElectricEnergyMeter',
    'electricBlindShade',
    'electricEnergySensor',
    'electricLock',
    'electricRainDoor',
    'electricWaterHeater',
    'emergencyButton',
    'enhancedLightingSystem',
    'evCharger',
    'evChargerDischarger',
    'floorHeater',
    'frequencyRegulation',
    'fuelCell',
    'gasMeter',
    'generalLighting',
    'homeAirConditioner',
    'humanDetectionSensor',
    'humiditySensor',
    'hvSmartElectricEnergyMeter',
    'hybridWaterHeater',
    'illuminanceSensor',
    'instantaneousWaterHeater',
    'lightingSystem',
    'lvSmartElectricEnergyMeter',
    'monoFunctionalLighting',
    'multipleInputPCS',
    'powerDistributionBoardMetering',
    'pvPowerGeneration',
    'refrigerator',
    'riceCooker',
    'smartElectricEnergySubMeter',
    'storageBattery',
    'switch',
    'temperatureSensor',
    'tv',
    'ventilationFan',
    'vocSensor',
    'washerDryer',
    'waterFlowMeter',
    'wattHourMeter',
  ],
}
